version: '3'

services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
  nodejs:
    build: .
    image: "node"
    volumes:
      - ./app:/usr/src/app 
    ports:
      - 127.0.0.1:5000:5000
    command: ["node", "/usr/src/app/app.js"]
